### ISSUE TITLE
Finish the zsh completion files

### ISSUE THREAD

**Issue by clawoflight** [clawoflight/aursec#12]
- [x] check `_aursec`
- [x] check `_aursec-hash`
- [x] write `_aursec-chain`

**Comment by Lifree** [comment]
Do you want me to look into this ?

**Comment by clawoflight** [comment]
Please :)

**Comment by Lifree** [comment]
Did my part with https://github.com/clawoflight/aursec/commit/e5f830548d89246a4345506469ca53c54bb9899f
