### ISSUE TITLE
aursec: configurable threshold

### ISSUE THREAD

**Issue by clawoflight** [clawoflight/aursec#14]
The threshold is currently hard-coded. It should be read from a config file or environment variable instead.

**Comment by Lifree** [comment]
i think we should add a config file... maybe we want other things in there as well (like stuff for the CLI-Dashboard)

**Comment by clawoflight** [comment]
Not sure yet, that adds more complexity than I feel like having.

Let's see how everything else goes and decide this later - it's just one
line of code either way.
