### ISSUE TITLE
aursec-chain: proper error handling

### ISSUE THREAD

**Issue by clawoflight** [clawoflight/aursec#18]
Because of the complexity of the involved processes, it would be very helpful to handle some errors explicitly and give descriptive error messages:
- check exit statuses of critical commands
- parse the json response where applicable

**Comment by Lifree** [comment]
improved by https://github.com/clawoflight/aursec/commit/3d7664a6e63e6e5df78d6fc2f5aeeabf46da25e7
parsing json response will not be possible with the current traps

**Comment by Lifree** [comment]
Done by https://github.com/clawoflight/aursec/commit/47f39c18f3ed5b9a84cc1bd54a772d81e4516714
