### ISSUE TITLE
aursec-hash: Find the optimal firejail ruleset

### ISSUE THREAD

**Issue by clawoflight** [clawoflight/aursec#20]
We need to minimize the danger of sourcing the PKGBUILD.
That means that we need to triple-check the firejail rules and actively try to break out until we are satisfied.

**Comment by clawoflight** [comment]
This is much easier since I added 713c762 :)

**Comment by Lifree** [comment]
can this be closed by https://github.com/clawoflight/aursec/commit/bbf247d3e2d4b6aaa34876a588f55a3cf237fd4e ?

**Comment by clawoflight** [comment]
I would say no, because there might be even more things to protect against.
Now that the tests work, the fun part of pentesting can begin :D

**Comment by clawoflight** [comment]
Some more ideas:
- [ ] Make sure that cloning vcs sources works, but limit other network traffic
