### ISSUE TITLE
aursec-chain: global lock for mining

### ISSUE THREAD

**Issue by clawoflight** [clawoflight/aursec#23]
We *may* run into problems at some point if multiple instances of `aursec-chain mine blocks N` are running at the same time.

We should check that and find a suitable global locking mechanism if necessary.

**Comment by Lifree** [comment]
What problems to you mean ?

**Comment by clawoflight** [comment]
When a user calls `aursec-chain mine blocks 5` while the timer runs, for
example.
Or a user runs `aursec-chain mine` in two different shells at the same time.

On 12/15/2016 02:53 PM, Lifree wrote:
> What problems to you mean ? 
> 

-- 
GPG fingerprint: 871F 1047 7DB3 DDED 5FC4 47B2 26C7 E577 EF96 7808

**Comment by Lifree** [comment]
closed by https://github.com/clawoflight/aursec/commit/498977a91958cebcf74324d31ddf934aaf961522
